apiVersion: batch/v1
kind: Job
metadata:
  name:  dronedelivery
  namespace: dronedelivery
spec:
  template:
    metadata:
      name:  name
    spec:
      containers:
      - name: dronedelivery
        image: anup8000/dronedelivery
      restartPolicy: Never
  backoffLimit: 4